[package]
name = "raw-acpi"
version = "0.0.2"
edition = "2015"
authors = ["JJ"]
license = "MIT OR Apache-2.0"
description = "Simply ACPI, in Rust."
repository = "https://github.com/JJtheJJpro/raw-acpi"
readme = "README.md"